
---
spring:
  jpa:
    generate-ddl: true

# turn off the security on the actuator end points as this is a demo app
management:
  security:
    enabled: false
    
# azure application insights
azure:
  application-insights:
    instrumentation-key: 96aaa22a-dce1-4648-9550-7b73b37cf529
